

# Colors
DEF_FG=006 
DEF_BG=235

# Directories
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_with_package_name
POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json Gemfile )
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

# Font Style
POWERLEVEL9K_MODE='nerdfont-complete'

# Prompt Name
POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false
POWERLEVEL9K_ALWAYS_SHOW_USER=false
POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %m"

# Context bg's
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="$DEF_FG"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="$DEF_BG"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="$DEF_FG"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="$DEF_BG"

# Rounds corners on main bar
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0BC"
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEF_BG - 2 ))}|%f"
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\uE0BA"
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEF_BG - 2 ))}|%f"

# Pushes the input below the bar
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

# Errors?
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Adds the arrow to the second line
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰\uF460 "

# Prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( root_indicator ssh vi_mode status dir_writable dir background_jobs   command_execution_time vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( )

# Ram
POWERLEVEL9K_RAM_BACKGROUND="$DEF_BG"
POWERLEVEL9K_RAM_FOREGROUND="$DEF_FG"
POWERLEVEL9K_RAM_ICON=""

# RVM
POWERLEVEL9K_CUSTOM_RVM="rvm current"
POWERLEVEL9K_CUSTOM_RVM_BACKGROUND="$DEF_BG"
POWERLEVEL9K_CUSTOM_RVM_FOREGROUND="$DEF_FG"

# Vi mode
POWERLEVEL9K_VI_INSERT_MODE_STRING=" INS"
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND="$DEF_BG"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND="red"
POWERLEVEL9K_VI_COMMAND_MODE_STRING=" NRM"
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND="$DEF_BG"
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND="green"

# Version Control
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="green"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="$DEF_BG"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="yellow"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="$DEF_BG"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="magenta"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="$DEF_BG"
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=""
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""
POWERLEVEL9K_VCS_GIT_ICON=""

# Directories
POWERLEVEL9K_DIR_HOME_BACKGROUND="$DEF_FG"
POWERLEVEL9K_DIR_HOME_FOREGROUND="$DEF_BG"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$DEF_FG"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="$DEF_BG"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$DEF_FG"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="$DEF_BG"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="$DEF_FG"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="$DEF_BG"
POWERLEVEL9K_DIR_WRITABLE_ICON="\uf023"

# Status
POWERLEVEL9K_STATUS_OK_FOREGROUND="$DEF_FG"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_OK_BACKGROUND="$DEF_BG"
POWERLEVEL9K_STATUS_OK_BACKGROUND="$(( $DEF_BG + 2 ))"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="$DEF_FG"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$DEF_BG"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$(( $DEF_BG + 2 ))"

# History
POWERLEVEL9K_HISTORY_FOREGROUND="$DEF_FG"

# Time
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uF017}" #  15:29
POWERLEVEL9K_TIME_FOREGROUND="$DEF_FG"
POWERLEVEL9K_TIME_BACKGROUND="$DEF_BG"

# Execution Time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="$DEF_BG"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$DEF_FG"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON="\uF017"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2

# BG Jobs
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="$DEF_BG"
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="$DEF_FG"
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
POWERLEVEL9K_BACKGROUND_JOBS_ICON="\uF46A"

# User
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="$DEF_FG"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="$DEF_BG"
POWERLEVEL9K_USER_ROOT_FOREGROUND="$DEF_FG"
POWERLEVEL9K_USER_ROOT_BACKGROUND="$DEF_BG"

# Root Indicator
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="$DEF_FG"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="magenta"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$DEF_BG"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$(( $DEF_BG + 2 ))"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$(( $DEF_BG - 2 ))"
POWERLEVEL9K_ROOT_ICON=$'\uF198'  # 

# SSH
POWERLEVEL9K_SSH_FOREGROUND="$DEF_FG"
POWERLEVEL9K_SSH_FOREGROUND="yellow"
POWERLEVEL9K_SSH_BACKGROUND="$DEF_BG"
POWERLEVEL9K_SSH_BACKGROUND="$(( $DEF_BG + 2 ))"
POWERLEVEL9K_SSH_BACKGROUND="$(( $DEF_BG - 2 ))"
POWERLEVEL9K_SSH_ICON="\uF489"  # 

# OS Icon
POWERLEVEL9K_OS_ICON_FOREGROUND="$DEF_FG"
POWERLEVEL9K_OS_ICON_BACKGROUND="$DEF_BG"

# Load
POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="$DEF_BG"
POWERLEVEL9K_LOAD_WARNING_BACKGROUND="$DEF_BG"
POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="$DEF_BG"
POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="red"
POWERLEVEL9K_LOAD_WARNING_FOREGROUND="yellow"
POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="green"
POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"

# Battery
POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND_COLOR="$DEF_BG"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="$DEF_BG"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="$DEF_BG"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="$DEF_BG"



