Plugin 'sheerun/vim-polyglot'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'tpope/vim-haml'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'tpope/vim-rails'
Plugin 'vim-ruby/vim-ruby'
Plugin 'othree/html5.vim'
Plugin 'gavocanov/vim-js-indent'
Plugin 'othree/yajs.vim'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'andreimaxim/vim-io'
Plugin 'ap/vim-css-color'
Plugin 'mxw/vim-jsx'
Plugin 'ekalinin/Dockerfile.vim'

let g:used_javascript_libs = 'underscore,vue,jquery'
