Plug 'sheerun/vim-polyglot'
Plug 'cakebaker/scss-syntax.vim'
Plug 'tpope/vim-haml'
Plug 'hail2u/vim-css3-syntax'
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'othree/html5.vim'
Plug 'gavocanov/vim-js-indent'
Plug 'othree/yajs.vim'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'andreimaxim/vim-io'
Plug 'ap/vim-css-color'
Plug 'mxw/vim-jsx'
Plug 'ekalinin/Dockerfile.vim'

let g:used_javascript_libs = 'underscore,vue,jquery'
