#!/bin/zsh

requests="$1"
executable="$2"
arguments="$@[3,-1]"
executable_command_with_arguments="$@[2,-1]"

if [[ ! $requests = <-> || $requests < 1 ]]; then
  echo "ERROR: First parameter must be the number of requests and greater than 1"
  exit 1
fi

if [[ ! "$( command -v $executable )" ]]; then
  echo "ERROR: Second parameter ($executable) must be an executable command"
  exit 1
fi

# Add silencing to curl
if [[ $executable = 'curl' && $arguments ]]; then
  additional_curl_args='-s -o /dev/null -w "%{time_total} seconds total | %{http_code} \n"'
  executable_command_with_arguments="$executable $additional_curl_args $arguments"
fi


echo "Beginning $requests calls to: \n$executable_command_with_arguments\n\n"

for i in `seq 1 $requests`
do
  eval $executable_command_with_arguments
  if [[ $requests < %i ]]; then
    break
  fi
done
